name: youprint
description: Text parser for ESC/POS Thermal Printer.
version: 1.0.6
homepage: https://github.com/youtaplibrary/youprint
publish_to: none

environment:
  sdk: ">=2.19.6 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  barcode_image: ">=2.0.2 <3.0.0"
  flutter:
    sdk: flutter
  image: ">=4.3.0 <5.0.0"
  zxing_lib: 1.1.2
  fluetooth:
    git:
      url: https://github.com/youtaplibrary/fluetooth.git
      ref: 0.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
