name: youprint
description: Text parser for ESC/POS Thermal Printer.
version: 1.0.6
homepage: https://github.com/youtaplibrary/youprint
repository: https://github.com/youtaplibrary/youprint
issue_tracker: https://github.com/youtaplibrary/youprint/issues

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  barcode_image: ">=2.0.2 <3.0.0"
  fluetooth:
    git:
      url: https://github.com/MyInOut/fluetooth_new
  flutter:
    sdk: flutter
  image: ">=4.3.0 <5.0.0"
  zxing_lib: 1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
